#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$DIR"

echo "=== [1/4] Derleniyor: Metal Shaders ==="
xcrun -sdk macosx metal -c Sources/DotoCore/Shaders/InkShaders.metal -o Sources/DotoCore/Shaders/InkShaders.air
xcrun -sdk macosx metallib Sources/DotoCore/Shaders/InkShaders.air -o Sources/DotoCore/Shaders/default.metallib
rm -f Sources/DotoCore/Shaders/InkShaders.air

echo "=== [2/4] Derleniyor: Swift Release ==="
swift build -c release

echo "=== [3/4] Paketleniyor: doto.app ==="
APP_BUNDLE="build/doto.app"
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# Copy binary
cp ".build/release/doto" "$APP_BUNDLE/Contents/MacOS/doto"

# Copy Info.plist
cp "Resources/Info.plist" "$APP_BUNDLE/Contents/Info.plist"

# Copy metallib
cp "Sources/DotoCore/Shaders/default.metallib" "$APP_BUNDLE/Contents/Resources/default.metallib"

# Copy resource bundles if generated by SPM
if [ -d ".build/release/Doto_DotoCore.bundle" ]; then
    cp -R ".build/release/Doto_DotoCore.bundle" "$APP_BUNDLE/Contents/Resources/"
fi

echo "=== [4/4] İmzalanıyor: Ad-hoc Codesign ==="
codesign --force --deep --sign - "$APP_BUNDLE"

echo "Tamamlandı: $APP_BUNDLE oluşturuldu!"
